### PR TITLE
fix(gulpfile.js): ensure all globbed paths are written in gulp.dest()

### PR DESCRIPTION
**Pull request by caitp**
Some regression in one of the gulpjs dependencies has broken gulp.dest in
newer versions, and rather than require the use of an older version of gulp,
this solution appears to work well in its place.

### CODE REVIEW

**Comment by caitp** [comment]
It's not clear why protractor is in package.json twice, but this fixes that too

**Comment by petebacondarwin** [comment]
@caitp - I believe the real problem was that Gulp was exiting too early, before all the files had been written.  I have fixed this in #4, by ensuring that all streams in a task have "ended" before the task ends.

I think this noop works because `map-stream` somehow slows down the task completion allowing the file system to catch up...

**Comment by caitp** [comment]
cool, did you push a fix?

**Comment by petebacondarwin** [comment]
No fix to gulp - the problem was with our code.

**Comment by caitp** [comment]
that's what I'm saying lol --- did you push the fix to the gulpfile

**Comment by caitp** [comment]
and for the record, the fact that it is fixable in our code does not mean this shouldn't be fixed in gulp

That is by definition a regression (worked before, didn't work after), requiring people to add workarounds for unjustified breaking changes is problematic, so you should file a bug anyways

**Comment by petebacondarwin** [comment]
https://github.com/angular/projects/pull/4

**Comment by petebacondarwin** [comment]
@caitp - I'm not sure I agree in this case.  If you have async tasks then you are supposed to let Gulp know: by returning a stream or calling a callback (or possibly returning a promise).  We weren't doing this but it just so happened that our code worked previously.

**Comment by caitp** [comment]
I don't think so, it shouldn't be the developers problem whether it's synchronous or not --- if you assume that all tasks are asynchronous, then you can avoid confusion and have a clear strategy for control flow --- if your tasks may or may not be synchronous, then that complicates things unnecessarily. I don't think they're trying to make things more complicated for people, that's clearly an error on their part.

**Comment by tbosch** [comment]
Just merged #4. Can we close this one?

**Pull request closed without merging**
